# Generated by Django 5.0.3 on 2024-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_category', models.CharField(max_length=30)),
                ('p_desc', models.CharField(max_length=100)),
                ('p_price', models.IntegerField(default=0)),
            ],
        ),
    ]
